version: '3'
services: 
  app:
    build: .
    working_dir: /app
    volumes:
        - .:/app
    expose:
      - 8080
    ports:
      - 8080:8080
    command: ./mvnw clean spring-boot:run

  nginx:
    container_name: springboot-nginx
    build:
      context: ./nginx/image/
    restart: always
    ports:
      - 8088:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    command: >
      /bin/sh -c "
                while ! nc -z -w1 app 8080;
                do
                  echo waiting app;
                  sleep 1;
                done;
                echo Started!;
                exec nginx -g 'daemon off;'
              "
