version: '3'
services: 
  app:
    build: .
    working_dir: /app
    volumes:
        - .:/app
    expose:
      - 8080
    ports:
      - 8080:8080
    command: ./mvnw clean spring-boot:run

  nginx:
    container_name: springboot-nginx
    image: nginx:1.13
    restart: always
    ports:
      - 8088:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
